### ISSUE TITLE
Add functions docstrings to all module functions in accordance with the Python conventions.

### ISSUE THREAD

**Issue by SerhiiYakhin** [Den4yk/Coins#1]
Add docstrings to all folowing functions.

https://github.com/Den4yk/Coins/blob/4d44423c13b70121693a2e80f51063086a4e6c24/coins.py#L8
https://github.com/Den4yk/Coins/blob/4d44423c13b70121693a2e80f51063086a4e6c24/coins.py#L13
https://github.com/Den4yk/Coins/blob/4d44423c13b70121693a2e80f51063086a4e6c24/coins.py#L16
https://github.com/Den4yk/Coins/blob/4d44423c13b70121693a2e80f51063086a4e6c24/coins.py#L19
https://github.com/Den4yk/Coins/blob/4d44423c13b70121693a2e80f51063086a4e6c24/coins.py#L35
https://github.com/Den4yk/Coins/blob/4d44423c13b70121693a2e80f51063086a4e6c24/coins.py#L54
https://github.com/Den4yk/Coins/blob/4d44423c13b70121693a2e80f51063086a4e6c24/coins.py#L62

**Comment by Den4yk** [comment]
https://github.com/Den4yk/Coins/commit/8fe07886841bf6d12526ff0a699d03d82a3ea64d
