### ISSUE TITLE
Change the comparison order in accordance with the Python conventions.

### ISSUE THREAD

**Issue by SerhiiYakhin** [Den4yk/Coins#2]
Change comparsion order in following code lines:

https://github.com/Den4yk/Coins/blob/4d44423c13b70121693a2e80f51063086a4e6c24/coins.py#L22

https://github.com/Den4yk/Coins/blob/4d44423c13b70121693a2e80f51063086a4e6c24/coins.py#L23

https://github.com/Den4yk/Coins/blob/4d44423c13b70121693a2e80f51063086a4e6c24/coins.py#L27

https://github.com/Den4yk/Coins/blob/4d44423c13b70121693a2e80f51063086a4e6c24/coins.py#L39

https://github.com/Den4yk/Coins/blob/4d44423c13b70121693a2e80f51063086a4e6c24/coins.py#L40

https://github.com/Den4yk/Coins/blob/4d44423c13b70121693a2e80f51063086a4e6c24/coins.py#L43

https://github.com/Den4yk/Coins/blob/4d44423c13b70121693a2e80f51063086a4e6c24/coins.py#L46

https://github.com/Den4yk/Coins/blob/4d44423c13b70121693a2e80f51063086a4e6c24/coins.py#L49

https://github.com/Den4yk/Coins/blob/4d44423c13b70121693a2e80f51063086a4e6c24/coins.py#L83

https://github.com/Den4yk/Coins/blob/4d44423c13b70121693a2e80f51063086a4e6c24/coins.py#L89

**Comment by Den4yk** [comment]
https://github.com/Den4yk/Coins/commit/483054d4a26e1cfd7bb2f7e7dde4622191a5705b
