### ISSUE TITLE
Change variables naming  in accordance with the Python conventions.

### ISSUE THREAD

**Issue by SerhiiYakhin** [Den4yk/Coins#3]
Change variable naming(Constant name must be **CONSTANT_NAME**) in following code lines:

https://github.com/Den4yk/Coins/blob/4d44423c13b70121693a2e80f51063086a4e6c24/coins.py#L83-L86

**Comment by Den4yk** [comment]
https://github.com/Den4yk/Coins/commit/16535152f0f8a70f9f8a9f50894a1cad772d0171
