### ISSUE TITLE
Remove magic digits from code.

### ISSUE THREAD

**Issue by SerhiiYakhin** [Den4yk/Coins#4]
Remove the presence of magic numbers in the following lines of code.
Also, it may be necessary to take out or rewrite part of the code (**ord(country[0][0]) - ord('A')**), to give it more self-documentation and clarity.

https://github.com/Den4yk/Coins/blob/4d44423c13b70121693a2e80f51063086a4e6c24/coins.py#L14

**Comment by Den4yk** [comment]
https://github.com/Den4yk/Coins/commit/e54dc1550405c0ea402480cef302836f471cdafb
https://github.com/Den4yk/Coins/commit/fc4a44c32cecffc93600fc9379260e8c713659ed
