### ISSUE TITLE
https://github.com/Den4yk/Coins/blob/master/coins.py#L35

### ISSUE THREAD

**Issue by IanaKhitsko** [Den4yk/Coins#7]
if (countries[elem['country_name']]['result_day'] == -1) and (len(countries[elem['country_name']]['completed_towns']) == countries[elem['country_name']]['towns_count']):
               
==
too long unreadable line

**Comment by Den4yk** [comment]
https://github.com/Den4yk/Coins/commit/efdd5ad1ff1dea3c766eb445da13bfd7f9e93131

**Comment by IanaKhitsko** [comment]
Работа принята
